config/routes.rb
Rails.application.routes.draw do
  root to: "clients#index"
  get 'pages/home'

  devise_for :users
  resources :clients do
    resources :inspections
  end

end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :inspections, :dependent => :destroy
  validates :email_one, uniqueness: true
  validates :first_name, :last_name, :street_address, :email_one, presence: true
end

app/models/inspection.rb
class Inspection < ActiveRecord::Base
  belongs_to :client
  validates :mail, :front_door, :security_system, :water_main, :water_heater,
  :garage_access_door, :garage_overhead_door, :outdoor_trash, :indoor_trash,
  :breaker_box, :smoke_detectors, :ceiling_fans, :humidistat,
  :thermostat, :cabinets_drawers, :refrigerator, :freezer, :garbage_disposal,
  :dishwasher, :faucets, :toilets, :doors_windows, :ceilings_walls, :screen_doors,
  :pool, :exterior, :pests, :general_cleanliness, :carpet_cleanliness, :window_cleanliness,
  :patio_cleanliness, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable,
    :trackable, :validatable

  validate :validate_invite, :on => :create
  attr_accessor :invite

  def validate_invite
   if self.invite != ENV["invitation_code"]
     self.errors[:base] << "The Invitation Code is Incorrect"
   end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :invite) }
  end
  
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :authenticate_user!

  def index
    @clients = Client.all
  end

  def show
    @client = Client.find(params[:id])
  end

  def new
    @client = Client.new
  end

  def edit
    @client = Client.find(params[:id])
  end

  def create
    @client = Client.new(client_params)
    if @client.save
      ClientMailer.welcome_email(@client).deliver_now
      redirect_to @client, notice: "New Client Created!"
    else
      render 'new'
    end
  end

  def update
    @client = Client.find(params[:id])
    if @client.update(client_params)
      redirect_to @client, notice: "Client Updated!"
    else
      render 'edit'
    end
  end

  def destroy
    @client = Client.find(params[:id])
    @client.destroy
    redirect_to clients_path, alert: "Client Destroyed!"
  end

  private

    def client_params
      params.require(:client).permit(:first_name, :last_name, :street_address, :unit,
      :phone_one, :phone_two, :email_one, :email_two)
    end

end

app/controllers/inspections_controller.rb
class InspectionsController < ApplicationController
  before_action :authenticate_user!

  def show
    @inspection = Inspection.find(params[:id])
    @client = Client.find(params[:client_id])
  end

  def index
    @client = Client.find(params[:client_id])
    @inspections = @client.inspections
  end

  def new
    @inspection = Inspection.new(:client => @client)
    @client = Client.find(params[:client_id])
  end

  def edit
    @inspection = Inspection.find(params[:id])
    @client = Client.find(params[:client_id])
  end

  def create
    @client = Client.find(params[:client_id])
    @inspection = Inspection.new(inspection_params)
    if @inspection.save
      ClientMailer.inspection_email(@client, @inspection).deliver_now
      redirect_to client_inspection_path(@client, @inspection), notice: "New Inspection Saved!"
    else
      render 'new'
    end
  end

  def update
    @client = Client.find(params[:client_id])
    @inspection = Inspection.find(params[:id])
    if @inspection.update(inspection_params)
      redirect_to client_inspection_path(@client, @inspection), notice: "Inspection Updated!"
    else
      render 'edit'
    end
  end

  def destroy
  end

  private

    def inspection_params
      params.require(:inspection).permit(:mail, :front_door, :security_system, :water_main,
      :water_heater, :garage_access_door, :garage_overhead_door, :outdoor_trash, :indoor_trash,
      :breaker_box, :washer, :dryer, :smoke_detectors, :ceiling_fans, :humidistat,
      :thermostat, :cabinets_drawers, :refrigerator, :freezer, :garbage_disposal, :dishwasher,
      :faucets, :toilets, :doors_windows, :ceilings_walls, :screen_doors, :pool, :exterior,
      :pests, :general_cleanliness, :carpet_cleanliness, :window_cleanliness, :patio_cleanliness, :comments, :client_id)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/inspections_helper.rb
module InspectionsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/clients/edit.html.erb
<div class="container">
  <%= form_for :client, url: client_path(@client), method: :patch do |f| %>
    <% if @client.errors.any? %>
      <div class="alert alert-dismissible alert-danger">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <h4 class="alert-validation">
          <%= pluralize(@client.errors.count, "error") %> prohibited
          this client from being updated:
        </h4>
          <% @client.errors.full_messages.each do |msg| %>
            <p><%= msg %></p>
          <% end %>
      </div>
    <% end %>
    <div class="form-group">
      <%= f.label :first_name, class:"form-label" %>
      <%= f.text_field :first_name, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :last_name, class:"form-label" %>
      <%= f.text_field :last_name, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :street_address, class:"form-label" %>
      <%= f.text_field :street_address, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :unit, class:"form-label" %>
      <%= f.text_field :unit, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :phone_one, "Primary Phone", class:"form-label" %>
      <%= f.text_field :phone_one, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :phone_two, "Secondary Phone", class:"form-label" %>
      <%= f.text_field :phone_two, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :email_one, "Primary Email", class:"form-label" %>
      <%= f.text_field :email_one, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :email_two, "Secondary Email", class:"form-label" %>
      <%= f.text_field :email_two, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.submit "Update Client", class:"btn btn-success" %>
    </div>
  <% end %>
  <%= link_to 'Delete Client', client_path(@client), method: :delete, data: { confirm: 'Are you sure? This will delete the client and their inspections.' }, class: "btn btn-danger" %>
</div>

app/views/clients/index.html.erb
<div class="container">
<%= link_to "Add Client", new_client_path, class:"btn btn-success" %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Client #</th>
        <th>Name</th>
      </tr>
    </thead>
    <tbody>
      <% @clients.each do |client| %>
        <tr>
          <td> <%= client.id %> </td>
          <td> <%= link_to "#{client.first_name} #{client.last_name}", client_path(client) %> </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/clients/new.html.erb
<div class="container">
  <%= form_for :client, url: clients_path do |f| %>
    <% if @client.errors.any? %>
      <div class="alert alert-dismissible alert-danger">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <h4 class="alert-validation">
          <%= pluralize(@client.errors.count, "error") %> prohibited
          this client from being saved:
        </h4>
          <% @client.errors.full_messages.each do |msg| %>
            <p><%= msg %></p>
          <% end %>
      </div>
    <% end %>
    <div class="form-group">
      <%= f.label :first_name, class:"form-label" %>
      <%= f.text_field :first_name, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :last_name, class:"form-label" %>
      <%= f.text_field :last_name, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :street_address, class:"form-label" %>
      <%= f.text_field :street_address, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :unit, class:"form-label" %>
      <%= f.text_field :unit, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :phone_one, "Primary Phone", class:"form-label" %>
      <%= f.text_field :phone_one, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :phone_two, "Secondary Phone", class:"form-label" %>
      <%= f.text_field :phone_two, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :email_one, "Primary Email", class:"form-label" %>
      <%= f.text_field :email_one, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :email_two, "Secondary Email", class:"form-label" %>
      <%= f.text_field :email_two, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.submit "Create Client", class:"btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/clients/show.html.erb
<div class="container">
  <div class="client-show">
    <legend><strong><%= "#{@client.first_name} #{@client.last_name}" %></strong></legend>
    <h4><strong>Address:</strong> <%= "#{@client.street_address} ##{@client.unit}" %></h4>
    <h4><strong>Primary Phone:</strong> <%= @client.phone_one %></h4>
    <h4><strong>Secondary Phone:</strong> <%= @client.phone_two %></h4>
    <h4><strong>Primary Email:</strong> <%= @client.email_one %></h4>
    <h4><strong>Secondary Email:</strong> <%= @client.email_two %></h4>
  </div>
  <%= link_to "Start Inspection For <br /> #{@client.first_name} #{@client.last_name}".html_safe, new_client_inspection_path(@client), class:"btn btn-success btn-sm inspection-btn"%>
  <%= link_to "View #{@client.first_name} #{@client.last_name}’s <br /> Inspections".html_safe, client_inspections_path(@client), class:"btn btn-warning btn-sm inspection-btn"%>
  <%= link_to "Edit #{@client.first_name} #{@client.last_name}’s <br /> Information".html_safe, edit_client_path(@client), class: "btn btn-default btn-sm inspection-btn button-height" %>
</div>

app/views/inspections/_form.html.erb
<div class="container">
  <%= form_for [@client, @inspection] do |f| %>
    <% if @inspection.errors.any? %>
      <div class="alert alert-dismissible alert-danger">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <h4 class="alert-validation">
          <%= pluralize(@inspection.errors.count, "error") %> prohibited
          this inspection from being saved:
        </h4>
          <% @inspection.errors.full_messages.each do |msg| %>
            <p><%= msg %></p>
          <% end %>
      </div>
    <% end %>
    <div class="form-group">
      <%= f.label :mail, class:"form-label" %>
      <%= f.text_field :mail, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :front_door, class:"form-label" %>
      <%= f.text_field :front_door, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :security_system, class:"form-label" %>
      <%= f.text_field :security_system, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :water_main, class:"form-label" %>
      <%= f.text_field :water_main, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :water_heater, class:"form-label" %>
      <%= f.text_field :water_heater, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :garage_access_door, class:"form-label" %>
      <%= f.text_field :garage_access_door, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :garage_overhead_door, class:"form-label" %>
      <%= f.text_field :garage_overhead_door, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :outdoor_trash, class:"form-label" %>
      <%= f.text_field :outdoor_trash, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :indoor_trash, class:"form-label" %>
      <%= f.text_field :indoor_trash, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :breaker_box, class:"form-label" %>
      <%= f.text_field :breaker_box, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :smoke_detectors, class:"form-label" %>
      <%= f.text_field :smoke_detectors, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :ceiling_fans, class:"form-label" %>
      <%= f.text_field :ceiling_fans, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :humidistat, class:"form-label" %>
      <%= f.text_field :humidistat, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :thermostat, class:"form-label" %>
      <%= f.text_field :thermostat, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :cabinets_drawers, class:"form-label" %>
      <%= f.text_field :cabinets_drawers, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :refrigerator, class:"form-label" %>
      <%= f.text_field :refrigerator, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :freezer, class:"form-label" %>
      <%= f.text_field :freezer, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :garbage_disposal, class:"form-label" %>
      <%= f.text_field :garbage_disposal, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :dishwasher, class:"form-label" %>
      <%= f.text_field :dishwasher, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :faucets, class:"form-label" %>
      <%= f.text_field :faucets, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :toilets, class:"form-label" %>
      <%= f.text_field :toilets, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :doors_windows, class:"form-label" %>
      <%= f.text_field :doors_windows, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :ceilings_walls, class:"form-label" %>
      <%= f.text_field :ceilings_walls, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :screen_doors, class:"form-label" %>
      <%= f.text_field :screen_doors, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :pool, class:"form-label" %>
      <%= f.text_field :pool, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :exterior, class:"form-label" %>
      <%= f.text_field :exterior, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :pests, class:"form-label" %>
      <%= f.text_field :pests, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :general_cleanliness, class:"form-label" %>
      <%= f.text_field :general_cleanliness, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :carpet_cleanliness, class:"form-label" %>
      <%= f.text_field :carpet_cleanliness, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :window_cleanliness, class:"form-label" %>
      <%= f.text_field :window_cleanliness, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :patio_cleanliness, class:"form-label" %>
      <%= f.text_field :patio_cleanliness, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :comments, class:"form-label" %>
      <%= f.text_field :comments, class:"form-control" %>
    </div>
    <%= f.hidden_field :client_id, :value => @client.id %>
    <div class="form-group">
      <%= f.submit class: "btn btn-danger create-inspection-btn" %>
    </div>
  <% end %>
</div>

app/views/inspections/edit.html.erb
<%= render 'form' %>

app/views/inspections/index.html.erb
<div class="container">
  <legend><strong><%= "#{@client.first_name} #{@client.last_name}'s Inspections" %></strong></legend>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Date of Inspection</th>
      </tr>
    </thead>
    <tbody>
      <% @inspections.each do |inspection| %>
        <tr>
          <td><%= link_to inspection.created_at.strftime("%B %d, %Y"), client_inspection_path(@client, inspection) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/inspections/new.html.erb
<%= render 'form' %>

app/views/inspections/show.html.erb
<div class="container inspection-show">
  <div class="">
    <legend><strong><%= "#{@client.first_name} #{@client.last_name}" %></strong></legend>
    <h4 class="inspection-date">Inspection #<%= "#{@inspection.id} #{@inspection.created_at.strftime('%B %d, %Y')}" %></h4>
    <label class="form-label">Front Door</label>
    <h4><%= @inspection.front_door %></h4>
    <label class="form-label">Mail</label>
    <h4><%= @inspection.mail %></h4>
    <label class="form-label">Security System</label>
    <h4><%= @inspection.security_system %></h4>
    <label class="form-label">Water Main</label>
    <h4><%= @inspection.water_main %></h4>
    <label class="form-label">Water Heater</label>
    <h4><%= @inspection.water_heater %></h4>
    <label class="form-label">Garage Access Door</label>
    <h4><%= @inspection.garage_access_door %></h4>
    <label class="form-label">Garage Overhead Door</label>
    <h4><%= @inspection.garage_overhead_door %></h4>
    <label class="form-label">Outdoor Trash</label>
    <h4><%= @inspection.outdoor_trash %></h4>
    <label class="form-label">Indoor Trash</label>
    <h4><%= @inspection.indoor_trash %></h4>
    <label class="form-label">Breaker Box</label>
    <h4><%= @inspection.breaker_box %></h4>
    <label class="form-label">Smoke Detectors</label>
    <h4><%= @inspection.smoke_detectors %></h4>
    <label class="form-label">Ceiling Fans</label>
    <h4><%= @inspection.ceiling_fans %></h4>
    <label class="form-label">Humidistat</label>
    <h4><%= @inspection.humidistat %></h4>
    <label class="form-label">Thermostat</label>
    <h4><%= @inspection.thermostat %></h4>
    <label class="form-label">Cabinets Drawers</label>
    <h4><%= @inspection.cabinets_drawers %></h4>
    <label class="form-label">Refrigerator</label>
    <h4><%= @inspection.refrigerator %></h4>
    <label class="form-label">Freezer</label>
    <h4><%= @inspection.freezer %></h4>
    <label class="form-label">Garbage Disposal</label>
    <h4><%= @inspection.garbage_disposal %></h4>
    <label class="form-label">Dishwasher</label>
    <h4><%= @inspection.dishwasher %></h4>
    <label class="form-label">Faucets</label>
    <h4><%= @inspection.faucets %></h4>
    <label class="form-label">Toilets</label>
    <h4><%= @inspection.toilets %></h4>
    <label class="form-label">Doors & Windows</label>
    <h4><%= @inspection.doors_windows %></h4>
    <label class="form-label">Ceilings & Walls</label>
    <h4><%= @inspection.ceilings_walls %></h4>
    <label class="form-label">Screen Doors</label>
    <h4><%= @inspection.screen_doors %></h4>
    <label class="form-label">Pool</label>
    <h4><%= @inspection.pool %></h4>
    <label class="form-label">Exterior</label>
    <h4><%= @inspection.exterior %></h4>
    <label class="form-label">Pests</label>
    <h4><%= @inspection.pests %></h4>
    <label class="form-label">General Cleanliness</label>
    <h4><%= @inspection.general_cleanliness %></h4>
    <label class="form-label">Carpet Cleanliness</label>
    <h4><%= @inspection.carpet_cleanliness %></h4>
    <label class="form-label">Window Cleanliness</label>
    <h4><%= @inspection.window_cleanliness %></h4>
    <label class="form-label">Patio Cleanliness</label>
    <h4><%= @inspection.patio_cleanliness %></h4>
    <label class="form-label">Comments</label>
    <h4><%= @inspection.comments %></h4>
  </div>
  <%= link_to "Edit Inspection", edit_client_inspection_path(:client_id => @client, :id => @inspection), class: "btn btn-default btn-sm inspection-btn button-height" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Home Watch</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= favicon_link_tag 'favicon.ico' %>
  <%= favicon_link_tag 'favicon.png', rel: 'apple-touch-icon', type: 'image/png' %>
</head>
<body>
  <div class="container-fluid">
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/pages/home"><i class="fa fa-user-secret" aria-hidden="true"></i><p id="brand-header">John’s Home Watch</p></a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><%= link_to "Home", pages_home_path %></li>
            <li><%= link_to "Clients", clients_path %></li>
            <% if user_signed_in? %>
              <li><%= link_to('Log Out', destroy_user_session_path, :method => :delete) %></li>
            <% else %>
              <li><%= link_to "Sign In", new_user_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
    <% if notice %>
        <div class="alert alert-dismissible alert-success">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <h4><%= notice %></h4>
      </div>
    <% end %>
    <% if alert %>
      <div class="alert alert-dismissible alert-danger">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <h4><%= alert %></h4>
      </div>
    <% end %>
    <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/pages/home.html.erb
<div class="brand-home">
  <i class="fa fa-user-secret watch-icon" aria-hidden="true"></i>
</div>